server:
  port: 8899
spring:
  application:
    name: e-commerce-api
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e_commerce?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 200309

  mail:
    host: smtp.163.com
    port: 465
    username: ${EMAIL_USER}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  data:
    ## redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      username:
      password:
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  ## 上传文件配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启自动驼峰命名

##文件配置
file:
  image:
    base-path: resources/image # 用相对路径(相对于项目运行目录)
